---
- hosts: all
  user: "{{ username | default(root) }}"

  tasks:

    - name: Reload supervisor
      become: yes
      service:
        name: supervisor
        state: reloaded

    - name: Restart nginx
      become: yes
      service: name=nginx state=restarted

    - name: Redis Restart
      become: yes
      service: name=redis-server state=restarted enabled=yes